# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will initiate a Veracode Static Analysis Pipeline scan, return a results.json and convert to SARIF for upload as a code scanning alert
name: Veracode Dependency Scanning
uses: veracode/veracode-sca@v2.1.6
with:
  github_token: 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
  quick: true
  url: https://github.com/appsec-devops/DV
  create-issues: true
  path: .
  allow-dirty: false
  recursive: true
  fail-on-cvss: 1
  min-cvss-for-issue: 1
  debug: false
